name: Run python test

on: 
    push: 
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Intall Python
              uses: actions/setup-python@v5
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest
                  pip install -r requirements.txt

            - name: Run tests with pytest
              run: |
                  pytest 

